### ISSUE TITLE
salt-master 2017.07.5 and newer

### ISSUE THREAD

**Issue by vquie** [martinhoefling/saltbeat#1]
Did anyone get this to work with salt-master 2017.07.05 and newer?

**Comment by martinhoefling** [comment]
Did it work before (using older versions) for you? I am not aware of any changes / incompatibilities.

**Comment by vquie** [comment]
It did work until 2017.07.3.

**Log**

	$ cat /var/log/saltbeat/saltbeat
	2018-06-06T09:13:51+02:00 INFO Home path: [/etc/saltbeat] Config path: [/etc/saltbeat] Data path: [/etc/saltbeat/data] Logs path: [/etc/saltbeat/logs]
	2018-06-06T09:13:51+02:00 INFO Setup Beat: saltbeat; Version: 5.0.0-alpha4
	2018-06-06T09:13:51+02:00 INFO Max Retries set to: 3
	2018-06-06T09:13:51+02:00 INFO Activated logstash as output plugin.
	2018-06-06T09:13:51+02:00 INFO Publisher name: salt
	2018-06-06T09:13:51+02:00 INFO Flush Interval set to: 1s
	2018-06-06T09:13:51+02:00 INFO Max Bulk Size set to: 2048
	2018-06-06T09:13:51+02:00 INFO Opening socket /var/run/salt/master/master_event_pub.ipc
	2018-06-06T09:13:51+02:00 INFO saltbeat start running.
	2018-06-06T09:13:51+02:00 INFO saltbeat is running! Hit CTRL-C to stop it.
	2018-06-06T09:13:51+02:00 CRIT EOF%!(EXTRA []interface {}=[])


**Debug Output**

    $ /etc/saltbeat/saltbeat -d debug
    panic: EOF
    
    goroutine 21 [running]:
    github.com/martinhoefling/saltbeat/vendor/github.com/elastic/beats/libbeat/logp.WTF(0xadba79, 0x3, 0x0, 0x0, 0x0)
    	/Users/martin/workspace/go/src/github.com/martinhoefling/saltbeat/vendor/github.com/elastic/beats/libbeat/logp/log.go:108 +0x16e
    github.com/martinhoefling/saltbeat/beater.(*Saltbeat).Setup.func1(0xc420144510)
    	/Users/martin/workspace/go/src/github.com/martinhoefling/saltbeat/beater/saltbeat.go:80 +0x225
    created by github.com/martinhoefling/saltbeat/beater.(*Saltbeat).Setup
    	/Users/martin/workspace/go/src/github.com/martinhoefling/saltbeat/beater/saltbeat.go:85 +0x269

**Comment by martinhoefling** [comment]
@vquiering  Can you try saltbeat 0.1.1 since the output on panic seems to be broken in 0.1.0.

**Comment by vquie** [comment]
There you go, @martinhoefling.

**Log**

    # cat /var/log/saltbeat/saltbeat
    2018-06-21T22:07:05+02:00 INFO Home path: [/etc/saltbeat] Config path: [/etc/saltbeat] Data path: [/etc/saltbeat/data] Logs path: [/etc/saltbeat/logs]
    2018-06-21T22:07:05+02:00 INFO Setup Beat: saltbeat; Version: 5.0.0-alpha4
    2018-06-21T22:07:05+02:00 INFO Max Retries set to: 3
    2018-06-21T22:07:05+02:00 INFO Activated logstash as output plugin.
    2018-06-21T22:07:05+02:00 INFO Publisher name: salt
    2018-06-21T22:07:05+02:00 INFO Flush Interval set to: 1s
    2018-06-21T22:07:05+02:00 INFO Max Bulk Size set to: 2048
    2018-06-21T22:07:05+02:00 INFO Opening socket /var/run/salt/master/master_event_pub.ipc
    2018-06-21T22:07:05+02:00 INFO saltbeat start running.
    2018-06-21T22:07:05+02:00 INFO saltbeat is running! Hit CTRL-C to stop it.
    2018-06-21T22:07:05+02:00 CRIT EOF%!(EXTRA []interface {}=[])


**Debug Output**

    # /etc/saltbeat/saltbeat -d debug
    panic: EOF
    
    goroutine 25 [running]:
    github.com/martinhoefling/saltbeat/vendor/github.com/elastic/beats/libbeat/logp.WTF(0xa94035, 0x3, 0x0, 0x0, 0x0)
    	/Users/martin/workspace/go/src/github.com/martinhoefling/saltbeat/vendor/github.com/elastic/beats/libbeat/logp/log.go:108 +0x164
    github.com/martinhoefling/saltbeat/beater.(*Saltbeat).Setup.func1(0xc42001c750)
    	/Users/martin/workspace/go/src/github.com/martinhoefling/saltbeat/beater/saltbeat.go:81 +0x23c
    created by github.com/martinhoefling/saltbeat/beater.(*Saltbeat).Setup
    	/Users/martin/workspace/go/src/github.com/martinhoefling/saltbeat/beater/saltbeat.go:71 +0x46b

**Comment by martinhoefling** [comment]
Does https://github.com/MaxBosse/saltbeat/tree/develop solve your issue?

**Comment by vquie** [comment]
@martinhoefling 
It looks like 3c5b234 addressed the issue we are having. Since I cannot compile this using golang 1.6, would you compile it so I can test that version?
We now switched to the saltstack logstash engine. There is no need to fix this for me now.

**Comment by martinhoefling** [comment]
v0.1.2 released, closing the issue.
